### PR TITLE
Build package manual as a part of CI tests

### PR DESCRIPTION
**Pull request by alex-konovalov**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@fingolfin could you please look if I did it correctly? I can't see where can I find the resulting manual, and the log for the manual build has many warnings.

**Comment by fingolfin** [comment]
To find the output, click on the "Checks" tab, then look for the "Artifacts" linke:
Screenshot 2022-05-04 at 11 35 47

**Comment by alex-konovalov** [comment]
Ok, thanks @fingolfin - now I see. Cross-refs to GAP main manuals not resolved - is it fine to ignore, since I will fix them when building the release locally, or is it a genuine problem?

**Comment by fingolfin** [comment]
This may be due to a problem @ThomasBreuer discovered yesterday

**Comment by ThomasBreuer** [comment]
The problem I observed yesterday was not about cross-references but about index entries.

**Review by fingolfin — APPROVED** [review]
I think this is good and should be merged.

Regarding the missing references: this is due to https://github.com/gap-actions/build-pkg-docs/issues/17 ; and of course a *real* missing/broken ref should be indicated in some way; see https://github.com/gap-actions/build-pkg-docs/issues/18 -- but that's something that should be dealt with in those actions. This PR here should just be merged as-is

**Comment by fingolfin** [comment]
I update this PR to some recent changes (newer version of some actions). Still think it should be merged

**Review by ThomasBreuer — APPROVED** [review]
Testing whether building the package manual works is certainly an improvement, thus I approve this pull request.

I am not sure what exactly shall be tested.
If the aim is to check the consistency of the package manual then perhaps it would be enough to create the HTML version, thus installing tex-live is not necessary.
(The question is then whether one wants to upload the current HTML version instead of `manual.pdf`.)

Also, the package manual cannot be built with the current setup if the package (manual) depends on a not yet released version of GAP or a version of a GAP package that has not yet been distributed with GAP.
I do not see an easy way to get automatic tests for such situations. Should the test then be regarded as passed or failed?
(The `PackageInfo.g` of the package lists which versions it requires. Thus one could extract which GAP version is needed, and try to install some stable branch of GAP if necessary. Likewise one could try to install the required/suggestd package versions, and their dependencies. I am not sure whether all this is desirable.)

**Pull request merged**
