### PR TITLE
Move from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by alex-konovalov**

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This has to be attempted in the same way like https://github.com/gap-packages/scscp/blob/master/.travis.yml does - start two SCSCP servers to interact with, and also collect coverage data from one of the servers.

**Comment by alex-konovalov** [comment]
Any tips @ssiccha ?

**Comment by ssiccha** [comment]
I have no idea what happens if you want to listen to ports inside the runner of an action. Maybe you need to do something special? It might help to use the debugging with tmate action here.

**Comment by alex-konovalov** [comment]
@ssiccha starting two SCSCP servers in the background happens to be as easy as
```
        run: |
          GAPROOT="$HOME/gap" GAPOPTS="-l $PWD/gaproot;" ./gapd.sh -p 26133
          GAPROOT="$HOME/gap" GAPOPTS="-l $PWD/gaproot;" ./gapd.sh -p 26134
```
so far, no coverage reports from the servers yet, and no building of the manual, but something to start with.

**Pull request merged**
