### PR TITLE
CI: track server code coverage

### LINKED ISSUE #35: Update CI to build manual and add coverage for the server code
TODO: 
- [x] add code coverage for the server
- [x] build the manual - PR #37

### PR DESCRIPTION
**Pull request by fingolfin**
Resolve #35

### CODE REVIEW

**Comment by fingolfin** [comment]
@alex-konovalov OK to merge?

**Review by alex-konovalov — APPROVED** [review]

**Comment by alex-konovalov** [comment]
@fingolfin thanks. I'm looking at why ANUPQ doesn't build in GAP 4.10 - since it works with GAP 4.10 in https://github.com/gap-packages/anupq

**Comment by fingolfin** [comment]
The GAP 4.10 tests run with the version of anupq bundled with GAP 4.10 . The tests in the anupq repository run with the latest anupq development version...

Moreover `ubuntu-latest` at GitHub recently was upgraded to a newer version, and so a newer GCC and libraries etc. This explains why it worked here before and now doesn't.

**Comment by alex-konovalov** [comment]
Ok, that's fixed in #44. However, still no server coverage - reopened #35

**Pull request merged**
